### PR TITLE
Resolved UnicodeDecodeError for weak aura imports

### PR DESCRIPTION
**Pull request by Sectimus**
[This issue](https://imgur.com/T3nb6uB) appears when using certain auras. After updating the encoding set in Wago.py to "ISO-8859-1" the issue has been resolved.

### CODE REVIEW

**Comment by AcidWeb** [comment]
This break other auras.

**Comment by Sectimus** [comment]
Strange, I didn't have any issues with my other auras, here's [my weakauras.lua](https://github.com/Sectimus/CurseBreaker/blob/wagoEncoder/Values/WeakAuras.lua)

**Comment by AcidWeb** [comment]
UTF-8 is correct encoding. Switching to ISO-8859-1 will break more stuff than fix.
Parser just need a little leeway. Pushed the workaround.

**Comment by AcidWeb** [comment]
Additionally this issue is caused by a fact that yours `WeakAuras.lua` is corrupted. There is a key there called `ztest` that contain not valid utf8 payload. And that key was not created by WA addon.

**Pull request closed without merging**
